### ISSUE TITLE
403 error when logging in.

### ISSUE THREAD

**Issue by fyxtro** [snypy/snypy-docker#22]
I created a new user and clicked on the verification url through the sendria page.
I got a succesful verification notification but now I get an 403 error when logging in. The webpage doesn't show this but the console does. 

I also cannot login with the default admin account. This gives me a 400 error in the console and says the login details are incorrect.

Snypy is behind a reverse proxy but currently is without certificate. (in the compose files I didn't set https either)
This reverse proxy is on a different host running nginx proxy manager.

Snypy is the only application running in this ubuntu 22.04.1 proxmox container.

**Comment by fyxtro** [comment]
My docker-compose.overides.yml:
```
version: "3"

services:
  api:
    environment:
      ALLOWED_HOSTS: "api.snypy.domain"
      SECRET_KEY: "changeme!"
      EMAIL_URL: "smtp://mail:1025"
      STATIC_URL: "http://127.0.0.1:8081/"
      CORS_ORIGIN_WHITELIST: "http://snypy.domain"
      REGISTER_VERIFICATION_URL: "http://snypy.domain/verify-user/"
      RESET_PASSWORD_VERIFICATION_URL: "http://snypy.domain/set-password/"
      REGISTER_EMAIL_VERIFICATION_URL: "http://snypy.domain/verify-email/"
    ports:
      - "8000:8000"
    volumes:
      - ./data/fixtures/:/fixtures/

  static:
    ports:
      - "8081:80"

  ui:
    environment:
      REST_API_URL: "http://api.snypy.domain"
    ports:
      - "8080:80"

  mail:
    image: msztolcman/sendria:v2.2.2.0
    ports:
      - "1080:1080"
```
